name: Publish Documentation with New Version
on:
  release:
    types: [ published ]
jobs:
  publish-new-doc-version:
    name: Publish Documentation with New Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.3
        with:
          ref: docs/main
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Setup doc deploy
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Deploy docs with pre-release version on pre-release event
        if: "github.event.release.prerelease"
        run: mike deploy --push ${GITHUB_REF_NAME}
      - name: Deploy docs with stable version on release event
        if: "!github.event.release.prerelease"
        run: mike deploy --push stable
      - name: Deploy docs with latest version on release event
        if: "!github.event.release.prerelease"
        run: mike deploy --push --update-aliases ${GITHUB_REF_NAME} latest